// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example for Android:
/// Replace these values with your own from Firebase Console
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: 'YOUR_IOS_API_KEY', 
    appId: 'YOUR_IOS_APP_ID', 
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET', 
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', 
    appId: 'YOUR_IOS_APP_ID', 
    messagingSenderId: 'YOUR_SENDER_ID', 
    projectId: 'YOUR_PROJECT_ID', 
    storageBucket: 'YOUR_STORAGE_BUCKET', // Opcional
    iosBundleId: 'com.example.delivery_ct',
  );
}

/*
INSTRUCCIONES PARA CONFIGURAR FIREBASE:

1. Ve a Firebase Console: https://console.firebase.google.com/
2. Crea un nuevo proyecto o selecciona uno existente
3. Agrega tu app Android/iOS al proyecto
4. Descarga google-services.json (Android) y GoogleService-Info.plist (iOS)
5. Coloca los archivos en:
   - Android: delivery_ct/android/app/google-services.json
   - iOS: delivery_ct/ios/Runner/GoogleService-Info.plist

6. Ejecuta el comando FlutterFire CLI para generar este archivo automáticamente:

   dart pub global activate flutterfire_cli
   flutterfire configure

   O configura manualmente reemplazando los valores arriba con los de tus archivos.

VALORES TÍPICOS DE EJEMPLO:
- apiKey: "AIzaSyC..."
- appId: "1:123456789:android:abc123def456"
- messagingSenderId: "123456789"
- projectId: "mi-proyecto-delivery"
- storageBucket: "mi-proyecto-delivery.appspot.com"
*/
